#!/bin/sh
set -e

if [ "$1" = "-n" ]; then
	extra="| del(.tasks[] | select(.deploy))"
	extra_note="(test) "
	shift
fi

pkg=$(basename "$1")
. "$pkg"/APKBUILD
yq ".environment.package = \"$pkg\" $extra" < build.yml | hut builds submit -n"$extra_note$pkgname $pkgver-r$pkgrel" -t "apkbuilds/$pkgname" -
